### ISSUE TITLE
Test incompatibility with upcoming zope.interface 5.1.0

### ISSUE THREAD

**Issue by jamadden** [plone/five.intid#17]
Which more carefully lets non-AttributeErrors propagate from descriptors. Here, it's a deliberately broken Acquisition wrapper:

```
File "//buildout.coredev/src/five.intid/five/intid/README.rst", line 361, in README.rst
Failed example:
    IKeyReference(item_c)
Expected:
    Traceback (most recent call last):
    ...
    TypeError: ('Could not adapt', <SimpleItem at c>,
    <InterfaceClass zope.keyreference.interfaces.IKeyReference>)
Got:
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest README.rst[112]>", line 1, in <module>
        IKeyReference(item_c)
    RuntimeError: Recursion detected in acquisition wrapper
```

The test just above this accesses `item_b.d` and expects the `RuntimeError`. It seems reasonable to expect the `RuntimeError` here as well.

cf https://github.com/zopefoundation/zope.interface/pull/201

**Comment by jensens** [comment]
+1 I will take care of it
